"""Build the ACP revision2 PPT slides.

Layout rule (per customer spec, 2026-07-17; band merge 2026-08-14):
  * ONE slide per (packet_type, band) -- band is the literal ACP band value
    (2.4/5, 6G merged into 5G at parse time in make_bt_tx_acp_revision2.py's
    read_all() -- see that comment for the full rationale), pa_supply is
    always 0 (ACP revision2 only ever used supply 0).
  * A single row of 13 images: offsets -6..+6 in ascending order (a subset
    of the full -10..+10 range generated by make_bt_tx_acp_revision2.py).
  * Same top-half-of-content-area placement as the Power/EVM deck -- the
    bottom half is left empty, reserved for ATE data later.
  * 2026-08-15 (customer request, supersedes the 2026-08-14 per-offset-
    adaptive design): ONE shared Y axis for the whole row again, computed
    from every real value shown on that slide -- Bench (every offset), ATE
    (if matched), and every offset's own spec Limit -- snapped to the
    nearest 10 with clearance (see make_bt_tx_acp_revision2.
    compute_shared_span). Real example that drove this: offset -6's real
    min=-52, offset +1's real max=1 -> shared span -60..10 ("한 페이지에
    들어가는 값들을 비교해보고 span을 고정"). The left-of-row Min/Max
    ruler (_add_ruler) is meaningful again with one shared span and has
    been restored.
  * Above each image: its own offset value as a label (e.g. "-6", "0"),
    bold, 14pt.
  * Title: "BT_TX_ACP_{packet_type}_{band}G" (e.g. "BT_TX_ACP_1DH5_2.4G").
"""

from __future__ import annotations

import datetime
import re
import statistics
from collections import defaultdict
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, MSO_AUTO_SIZE, PP_ALIGN
from pptx.util import Inches, Pt

import make_bt_tx_acp_revision2 as ACP_CHART
import make_bt_tx_pwr_revision2 as pwr_mod
import sys
from pathlib import Path as _Path
sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
import paths as bt_tx_paths

PATHS = bt_tx_paths.get_paths("BT_TX")
BASE_DIR = PATHS.base_dir
TEMPLATE_PATH = PATHS.ppt_template
ACP_PNG_DIR = PATHS.result_png_dir / "acp_revision2"
ACP_LEGEND_DIR = PATHS.result_png_dir / "acp_revision2_legend"

FNAME_RE = re.compile(
    r"packet_type\((?P<packet>[^)]+)\)_band\((?P<band>[^)]+)\)_"
    r"pa_supply\((?P<supply>[^)]+)\)_pa_slices\((?P<slices>[^)]+)\)_"
    r"pa_gain\((?P<gain>[^)]+)\)_dig_gain\((?P<dig>[^)]+)\)_"
    r"offset\((?P<offset>-?\d+)\)\.png"
)
LEGEND_FNAME_RE = re.compile(
    r"packet_type\((?P<packet>[^)]+)\)_band\((?P<band>[^)]+)\)_"
    r"pa_supply\((?P<supply>[^)]+)\)_pa_slices\((?P<slices>[^)]+)\)_"
    r"pa_gain\((?P<gain>[^)]+)\)_dig_gain\((?P<dig>[^)]+)\)_legend\.png"
)

FIXED_Y_MIN_DEFAULT = -50
FIXED_Y_MAX_DEFAULT = -20
# -6..6 excluding 0 -- offset 0's actual ACP values (~+20) fall well outside
# the narrowed [-50,-20] axis, so per customer feedback that chart is
# dropped; the freed slot becomes the legend cell instead.
OFFSETS = [o for o in range(-6, 7) if o != 0]  # 12 values


def get_axis_range_by_combo():
    """{(packet, band_str): (y_min, y_max)} -- ONE shared Y-axis span per
    (packet,band) slide (2026-08-15 customer request), computed from every
    real value shown on that slide: Bench (every offset), ATE (if any
    matched), and every offset's own spec Limit -- see
    make_bt_tx_acp_revision2.compute_shared_span's docstring for the full
    rationale. Supersedes both the 2026-07-19 fixed -50/-20 window this
    function used to return unconditionally, and the 2026-08-14 per-
    offset-adaptive design that briefly replaced it."""
    import bt_tx_acp_spec_lookup as spec_lookup
    import make_ate_tx_acp_revision2 as ate_acp_mod
    spec_table = spec_lookup.parse_spec(PATHS.bt_tx_spec_workbook or PATHS.spec_workbook)
    raw, pa_slices_seen, dig_gain_seen = ACP_CHART.read_all(PATHS.bench_dir)
    pa_slices_max = max(pa_slices_seen)
    dig_gain_max = max(dig_gain_seen)
    data = ACP_CHART.build_fixed_combos(raw, pa_slices_max, dig_gain_max)
    ate_idx = None
    if PATHS.extract_mode != "bench":
        try:
            ate_idx = ate_acp_mod.parse_ate_acp_records(ate_acp_mod.ATE_CSV)
        except (FileNotFoundError, OSError):
            ate_idx = None
    ranges = {}
    for combo, offset_map in data.items():
        packet, gain, band = combo
        specs = [spec_lookup.lookup(spec_table, packet, int(off)) for off in ACP_CHART.SLIDE_OFFSETS]
        extra_range = ate_acp_mod.get_ate_slide_extent(combo, offset_map, ate_idx)
        ranges[(packet, ACP_CHART.fmt_num(band))] = ACP_CHART.compute_shared_span(offset_map, extra_range, specs)
    return ranges


def get_offset_stats_by_combo():
    """offset_stats[(packet, band)][offset] = (mean, min, max, std), pooled
    across ALL frequencies for that offset -- the same population that
    offset's chart histograms, stacked by frequency color. Separate from
    get_axis_range_by_combo since the Y-axis itself stays fixed (no need to
    recompute it), but the stats table (2026-07-19, see
    share/PPT_FORMAT_STANDARD.md) needs real per-offset numbers."""
    raw, pa_slices_seen, dig_gain_seen = ACP_CHART.read_all(PATHS.bench_dir)
    pa_slices_max = max(pa_slices_seen)
    dig_gain_max = max(dig_gain_seen)
    data = ACP_CHART.build_fixed_combos(raw, pa_slices_max, dig_gain_max)
    offset_stats = {}
    for (packet, gain, band), offset_map in data.items():
        key = (packet, ACP_CHART.fmt_num(band))
        stats = {}
        for offset, freq_map in offset_map.items():
            pooled = [v for values in freq_map.values() for v in values]
            if pooled:
                stats[offset] = _stats(pooled)
        offset_stats[key] = stats
    return offset_stats

SLIDE_WIDTH_IN = 13.338542213473316
LEFT_MARGIN = 0.05
RIGHT_MARGIN = 0.05
# 2026-08-27 (user report): widened from 0.6in to match Harald/Cal's own
# LABEL_WIDTH (0.9in) -- see build_ppt_pwr_evm_revision2.py's identical
# comment for the full story (a narrower column needed the row_label text
# shrunk/wrap-disabled to fit; widening it lets it stay a normal 16pt).
RULER_WIDTH = 0.9
CELL_GAP_H = 0.03

# Format standard (established 2026-07-18 on the WL_TX deck, ported here
# 2026-07-19, see share/PPT_FORMAT_STANDARD.md): stats table under the
# title, chart grid fills only the top half of the real content area, an
# "ATE Data location" placeholder box reserves the bottom half.
#
# CONTENT_AREA_TOP/BOTTOM come from PPT-Template.pptx's own content
# placeholder (layout "1_", idx=12) -- verified identical to the WL_TX
# project's template (same file); re-derive if the template ever changes.
CONTENT_AREA_TOP = 1.5908508311461067
CONTENT_AREA_BOTTOM = CONTENT_AREA_TOP + 5.240927384076991
GRID_CONTENT_BOTTOM = CONTENT_AREA_TOP + (CONTENT_AREA_BOTTOM - CONTENT_AREA_TOP) / 2

TABLE_TOP = 1.05
TABLE_ROW_H = 0.16
TABLE_GRID_GAP = 0.08
ATE_GAP = 0.1
# Gap between the Bench+ATE table row and the chart grid below it -- see
# build_ppt_pwr_evm_revision2.py's TABLE_PLOT_GAP for why the plain
# TABLE_GRID_GAP wasn't enough (2026-07-20).
TABLE_PLOT_GAP = 0.35


def fmt_band(band: str) -> str:
    return f"{float(band):g}"


def discover(png_dir: Path):
    """Return data[(packet, band)][offset] = path."""
    data: dict = defaultdict(dict)
    for p in sorted(png_dir.glob("*.png")):
        m = FNAME_RE.match(p.name)
        if not m:
            print(f"  WARN: no match {p.name}")
            continue
        data[(m["packet"], m["band"])][int(m["offset"])] = p
    return data


def discover_legends(legend_dir: Path):
    """Return legends[(packet, band)] = path -- one standalone legend image
    per (packet,band) combo, shared across all 13 offset charts on that
    slide since they all use the same frequency/color set."""
    legends: dict = {}
    for p in sorted(legend_dir.glob("*.png")):
        m = LEGEND_FNAME_RE.match(p.name)
        if not m:
            print(f"  WARN: no match {p.name}")
            continue
        legends[(m["packet"], m["band"])] = p
    return legends


def _find_layout(prs, prefix, fallback):
    for i, layout in enumerate(prs.slide_layouts):
        if layout.name.startswith(prefix):
            return i
    return fallback


def _get_ph(slide, idx):
    for ph in slide.placeholders:
        if ph.placeholder_format.idx == idx:
            return ph
    return None


def _remove_placeholder(slide, idx: int) -> None:
    ph = _get_ph(slide, idx)
    if ph is not None:
        ph._element.getparent().remove(ph._element)


def _add_label(slide, left, top, width, height, text, size=10, bold=True, shrink_to_fit=False, wrap=True):
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.word_wrap = wrap
    tf.vertical_anchor = MSO_ANCHOR.MIDDLE
    tf.margin_left = 0
    tf.margin_right = 0
    tf.margin_top = 0
    tf.margin_bottom = 0
    if shrink_to_fit:
        tf.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    return box


def _add_ruler(slide, left, top, width, height, vmin: int, vmax: int, row_label=None):
    """row_label (2026-08-26): "Bench"/"ATE" text centered on this ruler --
    see build_ppt_pwr_evm_revision2.py's own _add_ruler docstring for why."""
    tick_h = 0.2
    _add_label(slide, left, top, width, tick_h, f"{vmax}", size=9, bold=True)
    _add_label(slide, left, top + height - tick_h, width, tick_h, f"{vmin}", size=9, bold=True)
    if row_label:
        # 2026-08-27: RULER_WIDTH widened to 0.9in (was 0.6in) so this can
        # stay a plain 16pt, matching Harald/Cal -- see RULER_WIDTH's own
        # comment and build_ppt_pwr_evm_revision2.py's _add_ruler
        # docstring for the two narrower-column workarounds this replaces.
        label_h = 0.4
        label_top = top + (height - label_h) / 2
        _add_label(slide, left, label_top, width, label_h, row_label, size=16, bold=True)


def _add_image_stretched(slide, path: Path, cell_left, cell_top, cell_width, cell_height):
    slide.shapes.add_picture(
        str(path), Inches(cell_left), Inches(cell_top), Inches(cell_width), Inches(cell_height)
    )


def _stats(values):
    """(mean, min, max, std) -- std is 0.0 for a single-point sample."""
    return (statistics.mean(values), min(values), max(values),
            statistics.stdev(values) if len(values) > 1 else 0.0)


def _set_cell(cell, text, size=6, bold=True, color=None):
    """A truly empty string (blank USL/LSL cell) makes PowerPoint render
    that ROW much taller than TABLE_ROW_H -- confirmed via win32com
    (11.52pt baseline vs 23.6pt with one empty cell): a run with no
    characters has nothing to measure, so PowerPoint falls back to a much
    larger default line height for that row instead of the 6pt we set on
    the (now-empty) run. A single space keeps the cell visually blank but
    gives PowerPoint an actual 6pt glyph to size the row against."""
    cell.vertical_anchor = MSO_ANCHOR.MIDDLE
    cell.margin_left = Pt(2)
    cell.margin_right = Pt(2)
    cell.margin_top = Pt(1)
    cell.margin_bottom = Pt(1)
    tf = cell.text_frame
    tf.word_wrap = True
    tf.text = text if text else " "
    for p in tf.paragraphs:
        p.alignment = PP_ALIGN.CENTER
        run = p.runs[0] if p.runs else p.add_run()
        run.font.size = Pt(size)
        run.font.bold = bold
        if color is not None:
            run.font.color.rgb = color


def _grid_col_widths(cell_width, n_cols, gap=CELL_GAP_H):
    """Data-column widths for the stats table so each column's LEFT edge
    lines up with its corresponding chart image below it. The image grid
    has a `gap` gap between images (cell_left advances by cell_width+gap
    each column); a plain pptx table has no such inter-column gap, so
    without this every column after the first drifts left of its image by
    an accumulating amount (up to 11*CELL_GAP_H =~ 0.33in by ACP's last
    column). Widening every column but the last by `gap` reproduces that
    same per-column advance; the last column stays at the plain
    cell_width so the table's total width still matches the grid's total
    width exactly (n*cell_width + (n-1)*gap)."""
    if n_cols <= 1:
        return [cell_width] * n_cols
    return [cell_width + gap] * (n_cols - 1) + [cell_width]


def _add_stats_table(slide, left, col_widths, top, header_label, headers, data_rows, colvar_rows=None,
                      row_h=None):
    """Stats table under the title, columns aligned with the chart grid
    below it. data_rows: [(row_label, [value_str,...])]. colvar_rows:
    [(row_label, [value_str,...], color)] -- like data_rows but bold+colored,
    one cell per column, NOT merged -- ACP's USL genuinely differs by offset
    within one slide (e.g. 1DH5: -20dBm at +/-2, -37dBm at +/-3..5), so
    unlike a truly-constant spec it can't be merged into a single cell (see
    share/PPT_FORMAT_STANDARD.md and this project's 2026-07-19
    clarification beyond that doc). row_h (2026-07-20, optional): per-row
    height in inches, default TABLE_ROW_H -- lets the ATE table (always
    header+2 rows) stretch to match a taller Bench table's total height
    when the two sit side by side. Returns the table's total height in
    inches."""
    colvar_rows = colvar_rows or []
    row_h = row_h if row_h is not None else TABLE_ROW_H
    n_cols = 1 + len(headers)
    n_rows = 1 + len(data_rows) + len(colvar_rows)
    total_width = sum(col_widths)
    total_height = row_h * n_rows

    gframe = slide.shapes.add_table(n_rows, n_cols, Inches(left), Inches(top),
                                     Inches(total_width), Inches(total_height))
    table = gframe.table
    table.first_row = False
    for i, w in enumerate(col_widths):
        table.columns[i].width = Inches(w)
    for r in range(n_rows):
        table.rows[r].height = Inches(row_h)

    _set_cell(table.cell(0, 0), header_label, size=6)
    for ci, h in enumerate(headers, start=1):
        _set_cell(table.cell(0, ci), h, size=6)

    row_i = 1
    for label, values in data_rows:
        _set_cell(table.cell(row_i, 0), label, size=6)
        for ci, v in enumerate(values, start=1):
            _set_cell(table.cell(row_i, ci), v, size=6, bold=True)
        row_i += 1

    for label, values, color in colvar_rows:
        _set_cell(table.cell(row_i, 0), label, size=6, color=color)
        for ci, v in enumerate(values, start=1):
            _set_cell(table.cell(row_i, ci), v, size=6, bold=True, color=color)
        row_i += 1

    return total_height


ATE_BORDER_COLOR = RGBColor(0xC0, 0x00, 0x00)
ATE_TEXT_COLOR = RGBColor(0xC0, 0x00, 0x00)
USL_COLOR = RGBColor(0xB0, 0x00, 0x00)


def _add_ate_placeholder(slide, left, top, width, height):
    """Empty bordered box labeled "ATE Data location" -- reserved space for
    ATE data to be added later (hard customer requirement)."""
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    box.line.color.rgb = ATE_BORDER_COLOR
    box.line.width = Pt(1.5)
    box.fill.background()
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Pt(6)
    tf.margin_top = Pt(4)
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.LEFT
    run = p.add_run()
    run.text = "ATE Data location"
    run.font.size = Pt(16)
    run.font.bold = True
    run.font.color.rgb = ATE_TEXT_COLOR
    return box


def _add_no_ate_box(slide, left, top, width, height):
    """Small per-column 'hole' for an offset with no ATE match (2026-07-20)
    -- unlike _add_ate_placeholder (one box spanning the whole row), this
    only covers ONE offset's cell so the other matched offsets on the same
    slide still show their ATE chart."""
    box = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(left), Inches(top), Inches(width), Inches(height))
    box.fill.background()
    box.line.color.rgb = ATE_BORDER_COLOR
    box.line.width = Pt(1)
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = MSO_ANCHOR.MIDDLE
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    run = p.add_run()
    run.text = "No ATE match"
    run.font.size = Pt(8)
    run.font.bold = True
    run.font.color.rgb = ATE_TEXT_COLOR


def _add_interleaved_table(slide, left, top, table_width, header_label, cond_labels,
                            bench_data_rows, ate_lookup, spec_rows=None):
    """ACP counterpart of build_ppt_pwr_evm_revision2._add_interleaved_table
    -- ONE combined table with Bench/ATE columns ALTERNATING per offset
    (2026-07-20 customer request: "Table이 Bench랑 ATE랑 번갈아가면서
    나오도록"). See that module's docstring for the full column-merging
    rationale. Returns the table's total height in inches."""
    spec_rows = spec_rows or []
    n_cond = len(cond_labels)
    n_data_cols = 2 * n_cond
    n_cols = 1 + n_data_cols
    n_rows = 2 + len(bench_data_rows) + len(spec_rows)

    grid_width = table_width - RULER_WIDTH
    cell_width = (grid_width - (n_data_cols - 1) * CELL_GAP_H) / n_data_cols
    col_widths = [RULER_WIDTH] + _grid_col_widths(cell_width, n_data_cols)
    total_width = sum(col_widths)
    total_height = TABLE_ROW_H * n_rows

    gframe = slide.shapes.add_table(n_rows, n_cols, Inches(left), Inches(top),
                                     Inches(total_width), Inches(total_height))
    table = gframe.table
    table.first_row = False
    for i, w in enumerate(col_widths):
        table.columns[i].width = Inches(w)
    for r in range(n_rows):
        table.rows[r].height = Inches(TABLE_ROW_H)

    _set_cell(table.cell(0, 0), header_label, size=6)
    _set_cell(table.cell(1, 0), "", size=6)
    for ci, label in enumerate(cond_labels):
        c1 = 1 + ci * 2
        merged = table.cell(0, c1)
        merged.merge(table.cell(0, c1 + 1))
        _set_cell(merged, label, size=6)
        _set_cell(table.cell(1, c1), "Bench", size=6)
        _set_cell(table.cell(1, c1 + 1), "ATE", size=6)

    row_i = 2
    for label, bench_vals in bench_data_rows:
        _set_cell(table.cell(row_i, 0), label, size=6)
        for ci in range(n_cond):
            c1 = 1 + ci * 2
            _set_cell(table.cell(row_i, c1), bench_vals[ci], size=6, bold=True)
            _set_cell(table.cell(row_i, c1 + 1), ate_lookup(label, ci), size=6, bold=True)
        row_i += 1

    for label, values, color in spec_rows:
        _set_cell(table.cell(row_i, 0), label, size=6, color=color)
        for ci in range(n_cond):
            c1 = 1 + ci * 2
            merged = table.cell(row_i, c1)
            merged.merge(table.cell(row_i, c1 + 1))
            _set_cell(merged, values[ci], size=6, bold=True, color=color)
        row_i += 1

    return total_height


def _add_ate_images(slide, usable_left, cell_width, top, height, present, ate_data):
    """Per offset column: the ATE chart image (matched) or a small
    _add_no_ate_box (not matched). present: [(offset, bench_path), ...]."""
    for ci, (off, _path) in enumerate(present):
        cell_left = usable_left + RULER_WIDTH + ci * (cell_width + CELL_GAP_H)
        info = ate_data.get(off)
        png = info["png"] if info else None
        if png is not None:
            _add_image_stretched(slide, png, cell_left, top, cell_width, height)
        else:
            _add_no_ate_box(slide, cell_left, top, cell_width, height)


def add_acp_slide(prs, layout_idx, title_text, offset_map, offset_stats, legend_path=None,
                   y_min=FIXED_Y_MIN_DEFAULT, y_max=FIXED_Y_MAX_DEFAULT, get_spec=None, ate_data=None):
    """Single row: offsets -6..6 (excluding 0) in order, ruler at the left
    (Min/Max only), one extra rightmost cell -- the same width/height as
    every offset cell -- holding the combo's standalone legend image.
    Stats table (Mean/Min/Max/Std per offset, plus a per-column USL row if
    get_spec is given) sits under the title; ATE placeholder box fills the
    reserved bottom half (or, when ate_data is given -- {offset: {"png":..,
    "stats":..} or None} -- an interleaved Bench/ATE table + a two-row
    Bench/ATE chart grid, 2026-07-20, see _add_interleaved_table)."""
    slide = prs.slides.add_slide(prs.slide_layouts[layout_idx])
    ph_title = _get_ph(slide, 1) or _get_ph(slide, 0)
    if ph_title:
        ph_title.text = title_text
    _remove_placeholder(slide, 12)

    present = [(off, offset_map[off]) for off in OFFSETS if off in offset_map]
    n_cols = len(present) + (1 if legend_path is not None else 0)

    usable_left = LEFT_MARGIN
    usable_right = SLIDE_WIDTH_IN - RIGHT_MARGIN
    grid_width = usable_right - usable_left - RULER_WIDTH
    cell_width = (grid_width - (n_cols - 1) * CELL_GAP_H) / n_cols

    headers = [f"{off}" for off, _path in present]
    mean_std, min_max = [], []
    for off, _path in present:
        s = offset_stats.get(off)
        if s:
            mean_std.append(f"{s[0]:.2f}±{s[3]:.2f}")
            min_max.append(f"{s[1]:.2f} / {s[2]:.2f}")
        else:
            mean_std.append(""); min_max.append("")
    data_rows = [("Mean±Std", mean_std), ("Min/Max", min_max)]

    colvar_rows = []
    if get_spec is not None:
        usl_vals, lsl_vals = [], []
        any_usl = any_lsl = False
        for off, _path in present:
            spec = get_spec(off)
            lsl, usl = spec if spec else (None, None)
            usl_vals.append(f"{usl:g}" if usl is not None else "")
            lsl_vals.append(f"{lsl:g}" if lsl is not None else "")
            any_usl = any_usl or usl is not None
            any_lsl = any_lsl or lsl is not None
        if any_usl:
            colvar_rows.append(("USL", usl_vals, USL_COLOR))
        if any_lsl:
            colvar_rows.append(("LSL", lsl_vals, USL_COLOR))

    if ate_data is not None:
        # 2026-07-20 customer request: ONE combined table with Bench/ATE
        # columns ALTERNATING per offset ("Table이 Bench랑 ATE랑 번갈아가면서
        # 나오도록") -- see _add_interleaved_table's docstring. Chart grid
        # below is unaffected (still the original two full-width stacked
        # rows, Bench row on top / ATE row + legend below).
        def ate_lookup(label, ci, _present=present):
            off, _path = _present[ci]
            info = ate_data.get(off)
            stats = info["stats"] if info else None
            if not stats:
                return ""
            return f"{stats[0]:.2f}±{stats[3]:.2f}" if label == "Mean±Std" else f"{stats[1]:.2f} / {stats[2]:.2f}"

        table_h = _add_interleaved_table(slide, usable_left, TABLE_TOP, usable_right - usable_left,
                                          "Offset", headers, data_rows, ate_lookup, spec_rows=colvar_rows)
    else:
        col_widths = [RULER_WIDTH] + _grid_col_widths(cell_width, len(present))
        table_h = _add_stats_table(slide, usable_left, col_widths, TABLE_TOP, "Offset", headers,
                                    data_rows, colvar_rows=colvar_rows)

    if ate_data is not None:
        # Plot stays the ORIGINAL two full-width stacked rows (Bench row on
        # top, ATE row + legend below) -- 2026-07-20 confirmed final: only
        # the table moves side by side, never the chart grid.
        plots_top = TABLE_TOP + table_h + TABLE_PLOT_GAP
        plots_bottom = CONTENT_AREA_BOTTOM
        bench_image_h = (plots_bottom - plots_top - ATE_GAP) / 2
        bench_image_top = plots_top
        ate_image_top = bench_image_top + bench_image_h + ATE_GAP
        ate_image_h = plots_bottom - ate_image_top

        # 2026-08-15 (customer request): axis is one shared span for the
        # WHOLE slide again (see make_bt_tx_acp_revision2.
        # compute_shared_span), so the left-of-row Min/Max ruler is
        # accurate again -- restored (was dropped 2026-08-14 during the
        # brief per-offset-adaptive design).
        _add_ruler(slide, usable_left, bench_image_top, RULER_WIDTH, bench_image_h, y_min, y_max, row_label="Bench")
        for ci, (off, path) in enumerate(present):
            cell_left = usable_left + RULER_WIDTH + ci * (cell_width + CELL_GAP_H)
            _add_image_stretched(slide, path, cell_left, bench_image_top, cell_width, bench_image_h)

        if legend_path is not None:
            legend_left = usable_left + RULER_WIDTH + len(present) * (cell_width + CELL_GAP_H)
            pic = slide.shapes.add_picture(str(legend_path), Inches(legend_left), Inches(bench_image_top),
                                            width=Inches(cell_width))
            legend_h_in = pic.height / 914400
            if legend_h_in > bench_image_h:
                pic.height = Inches(bench_image_h)
                pic.width = int(pic.height * pic.image.size[0] / pic.image.size[1])
            pic.top = Inches(bench_image_top)

        _add_ruler(slide, usable_left, ate_image_top, RULER_WIDTH, ate_image_h, y_min, y_max, row_label="ATE")
        _add_ate_images(slide, usable_left, cell_width, ate_image_top, ate_image_h, present, ate_data)
    else:
        content_top = TABLE_TOP + table_h + TABLE_GRID_GAP
        content_bottom = GRID_CONTENT_BOTTOM
        image_h = content_bottom - content_top

        _add_ruler(slide, usable_left, content_top, RULER_WIDTH, image_h, y_min, y_max)

        for ci, (off, path) in enumerate(present):
            cell_left = usable_left + RULER_WIDTH + ci * (cell_width + CELL_GAP_H)
            _add_image_stretched(slide, path, cell_left, content_top, cell_width, image_h)

        if legend_path is not None:
            legend_left = usable_left + RULER_WIDTH + len(present) * (cell_width + CELL_GAP_H)
            # Match cell WIDTH only -- forcing the height too (like the offset
            # charts) stretched the legend vertically and distorted the text.
            pic = slide.shapes.add_picture(str(legend_path), Inches(legend_left), Inches(content_top),
                                            width=Inches(cell_width))
            legend_h_in = pic.height / 914400
            if legend_h_in > image_h:
                pic.height = Inches(image_h)
                pic.width = int(pic.height * pic.image.size[0] / pic.image.size[1])
            pic.top = Inches(content_top)

        _add_ate_placeholder(slide, usable_left, GRID_CONTENT_BOTTOM + ATE_GAP,
                              usable_right - usable_left, CONTENT_AREA_BOTTOM - (GRID_CONTENT_BOTTOM + ATE_GAP))

    return slide


def main() -> None:
    prs = Presentation(TEMPLATE_PATH)
    content_layout_idx = _find_layout(prs, "1_", 5)

    print("Discovering ACP PNGs...")
    data = discover(ACP_PNG_DIR)
    print(f"  {len(data)} (packet, band) groups")
    legends = discover_legends(ACP_LEGEND_DIR)
    print(f"  {len(legends)} legend images")
    print("Computing per-combo Y-axis range...")
    axis_range_by_combo = get_axis_range_by_combo()
    print("Computing per-offset stats...")
    offset_stats_by_combo = get_offset_stats_by_combo()

    print("Parsing ACP spec limits...")
    import bt_tx_acp_spec_lookup as spec_lookup
    spec_table = spec_lookup.parse_spec(PATHS.bt_tx_spec_workbook or PATHS.spec_workbook)

    for packet, band in sorted(data.keys()):
        # 2026-08-27 (customer request via LEE SeokJin): every slide title
        # must show its HPA voltage. ACP only ever uses ONE fixed supply
        # (FIXED_SUPPLY -- see this module's own docstring), so unlike
        # Power/DEVM/FreqAcc/BW's Band2.4G there's no combine-vs-split
        # question here -- just always append it.
        title = f"BT_TX_ACP_{packet}_{fmt_band(band)}G_HPA_{pwr_mod.hpa_label(ACP_CHART.FIXED_SUPPLY)}"
        y_min, y_max = axis_range_by_combo.get((packet, band), (FIXED_Y_MIN_DEFAULT, FIXED_Y_MAX_DEFAULT))
        offset_stats = offset_stats_by_combo.get((packet, band), {})

        def get_spec(off, _packet=packet):
            return spec_lookup.lookup(spec_table, _packet, int(off))

        add_acp_slide(prs, content_layout_idx, title, data[(packet, band)], offset_stats,
                      legend_path=legends.get((packet, band)), y_min=y_min, y_max=y_max, get_spec=get_spec)

    report_dir = PATHS.report_dir
    report_dir.mkdir(parents=True, exist_ok=True)
    out_path = report_dir / f"{datetime.date.today().isoformat()}_BT_TX_ACP_Revision2.pptx"
    prs.save(out_path)
    print(f"Saved: {out_path}")


if __name__ == "__main__":
    main()
